### ISSUE TITLE
HA Reboot requires Integration disable/enable

### ISSUE THREAD

**Issue by salty2011** [mihailescu2m/hass-airtouch4-platform#1]
After a reboot of home assistant the integration has an error stating it is unable to contact the AirTouch controller. Disabling and re-enabling the integration resolves the issue.

Have looked at the home assistant logs but nothing is posted in there to explain the issue

**Comment by salty2011** [comment]
Ok looks like its timing out talking to the polyair on restart. Found the following in my HA logs

ERROR (MainThread) [custom_components.polyaire.airtouch4] Cannot connect to AirTouch host, giving up...

**Comment by kcd83** [comment]
Looks like an easy fix here

https://github.com/mihailescu2m/hass-airtouch4-platform/blob/main/custom_components/polyaire/airtouch4.py#L55

I wonder what a typical integration retry back-off strategy should be... 😕

**Comment by danielallin** [comment]
Having the same issue, enable/disable fixes after reboot/restart. Would love to see this fixed as it works great :-)

**Comment by brine0m** [comment]
I havent had this issue in a long while. prolly safe o close this issue

**Comment by danielallin** [comment]
I don't appear to have had this issue since rebuilding my home assistant on a RPi4 (previously running on a RPi3). So much faster if you can get your hands on one...
