### ISSUE TITLE
Room Thermostats all show as Cooling even when heating

### ISSUE THREAD

**Issue by kylecwhite** [mihailescu2m/hass-airtouch4-platform#3]
I have Airtouch4 in home assistant then linked to HomeKit. Firstly, it works great thanks.

But the room thermostats in HomeKit all display 'Cooling to ..' when turned on. This occurs no matter the mode of the main thermostat. For example we now have heating running but rooms still read as cooling.

Is it possible to adjust this?

Thanks

**Comment by mihailescu2m** [comment]
I will have a look soon, can you post screenshots and logs? This should not happen afaik.

**Comment by kylecwhite** [comment]
Ok. I have taken screen shots from HA, Homeklt and made a file of logs..... Let me know if there is anything else to provide. Thanks. 

By the way, I bought / setup HA just for this plugin and overall it has been great.
<img width="1147" alt="Screen Shot 2022-06-17 at 7 49 31 pm" src="https://user-images.githubusercontent.com/63991956/174277172-6584cb1c-6108-4245-b195-592210a14578.png">
[HA Logs.docx](https://github.com/mihailescu2m/hass-airtouch4-platform/files/8926604/HA.Logs.docx)

<img width="505" alt="Screen Shot 2022-06-17 at 7 51 51 pm" src="https://user-images.githubusercontent.com/63991956/174277191-418cd724-4a30-4aa5-b21f-05cc30fb308f.png">
<img width="146" alt="Screen Shot 2022-06-17 at 7 52 09 pm" src="https://user-images.githubusercontent.com/63991956/174277195-29a6429c-3a78-4945-8300-ca3379402c51.png">

**Comment by mihailescu2m** [comment]
How is it linked to HomeKit?

**Comment by kylecwhite** [comment]
<img width="284" alt="Screen Shot 2022-06-17 at 8 08 51 pm" src="https://user-images.githubusercontent.com/63991956/174277650-d447f1b2-53a1-4744-8b02-829e60c7ec70.png">

**Comment by mihailescu2m** [comment]
I would assume then it's an issue with this plugin. So either ask for help there, or even better use the homebridge Airtouch 4 plugin (as it happens, I am also the author of that too :P) - they can "coexist" peacefully.

**Comment by kylecwhite** [comment]
Ok I will ask for help in the bridge plugin. 

I had the home bridge plugin but could never get it to work properly. I noticed you started this HA plugin for airtouch4 so I decided to try it out. 

The HA airtouch4 plugin works great. Other than the cooling versus heating. Considering the state of HomeKit compatible AC controllers in Australia I am pretty please with current situation.
