### ISSUE TITLE
Sensors not updated automatically when changes are made on wall controllers

### ISSUE THREAD

**Issue by spry-salt** [mihailescu2m/hass-airtouch4-platform#5]
Updated to version 1.3 (PUSH) which seems to work except that sensors aren't updating automatically when changes are made to target temperature or zone on/off state, either on the AirTouch 4 tablet or on ITC switches. 

I can force updates to happen for all zones by using NodeRed to change the target temperature of a single zone by 0.1 degree. I've set NodeRed to do that every minute. Hopefully you can find some way of automating that in the integration?

**Comment by mihailescu2m** [comment]
Version 1.3 changed entities id. Did you update your configuration accordingly?
E.g. `fan.living` should be renamed to `fan.damper_living`, `climate.master` should be renamed to `climate.itc_master`, and `climate.daikin` should be `climate.ac_daikin` - *in all scripts, cards and automations*.

**Comment by spry-salt** [comment]
I updated all entities, yes. I'm only using ITC mode for all zones if that makes any difference?

**Comment by mihailescu2m** [comment]
No, it makes no difference, I am not able  to reproduce.
(I am also now over 12 hours without losing the connection...)
Try deleting the integration and add it again...

**Comment by spry-salt** [comment]
Thanks. I deleted the instance, then the integration, restarted, re-downloaded the integration, re-established the instance, rebooted the AirTouch tablet and restarted HA. 

What I observe now is that if I make changes to zone on/off or zone temperature in HA they show on the tablet right away. But if I make changes to those things on the tablet, they don't show in HA until I make any kind of change in HA. 

For example, I can use HA to turn on all the zones and set their temperatures to 20 degrees - those changes all show on the tablet right away. Then on the tablet I can change all the zone temperatures to 19 degrees and turn them all off - those changes don't show in HA at all. Then if I make one change in HA, all those changes I made in the tablet immediately appear in HA.

**Comment by spry-salt** [comment]
This morning when NodeRed switched on the AirTouch system as scheduled, the sensor readings in HA didn't match those on the AirTouch tablet. HA wasn't getting updated readings from the main temperature sensor in the airconditioning unit so it was making wrong calculations. 

Is there any testing I can do, or data I can provide, that would be helpful to you with debugging? I love this integration and it's so useful in my home automation. Thanks.

**Comment by tomwaldnz** [comment]
I'm also seeing Home Assistant isn't getting the latest temperatures from the Airtouch4. I'll give it a couple of days, but I may to roll back to v1.2 until this is sorted. I'm happy to help with any information / debugging / etc.

**Comment by mihailescu2m** [comment]
Should be fixed starting with v.1.3.2
