### ISSUE TITLE
Current Temperature as its own sensor

### ISSUE THREAD

**Issue by brine0m** [mihailescu2m/hass-airtouch4-platform#6]
**Problem Statement**
When using something like Dwains dashboard the current temperature is not display while AC unit is set to off, and when it is on it will display the desired temp instead of the current temp

**Possible Fix**
Not entirely sure, but perhaps the below

- Move current_temperature attribute to its own sensor and make the attribute temperature
- on the itc sensor rename temperature to target_temperature

**Comment by mihailescu2m** [comment]
This seems like an issue with Dwains dashboard. The climate entity description is clear, and I will not move an attribute that is defined in the climate entity to a sensor because of a theme that might not be conformant.
I suggest you create a virtual sensor using templates.
